ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CHOICE';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SURVEY';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'WIKI';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GLOSSARY';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'WORKSHOP';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DATABASE';
