"use client";
import {FormEvent,use,useEffect,useRef,useState} from "react";import {CheckCircle2,Eraser,FileSignature,LoaderCircle} from "lucide-react";import "./contract.css";
type Contract={title:string;content:string;studentName:string;signerName:string|null;course:string;teacher:string;expiresAt:string;signedAt:string|null};
export default function ContractPage({params}:{params:Promise<{token:string}>}){
  const{token}=use(params),[data,setData]=useState<Contract|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),signed=useRef(false);
  useEffect(()=>{fetch(`/api/contracts/${token}`).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d.contract)}).catch(e=>setError(e.message))},[token]);
  function pos(e:React.PointerEvent<HTMLCanvasElement>){const c=canvas.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
  function start(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;signed.current=true;const c=canvas.current!,p=pos(e),x=c.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y);c.setPointerCapture(e.pointerId)}
  function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const c=canvas.current!,p=pos(e),x=c.getContext("2d")!;x.lineWidth=3;x.lineCap="round";x.strokeStyle="#17152a";x.lineTo(p.x,p.y);x.stroke()}
  function clear(){canvas.current?.getContext("2d")?.clearRect(0,0,900,260);signed.current=false}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!signed.current){setError("Dibuja la firma antes de continuar.");return}setBusy(true);setError("");const form=new FormData(e.currentTarget),blob=await new Promise<Blob|null>(resolve=>canvas.current!.toBlob(resolve,"image/png"));if(blob)form.set("signature",blob,"firma.png");form.set("consent","true");const r=await fetch(`/api/contracts/${token}`,{method:"POST",body:form}),d=await r.json();if(r.ok)setDone(true);else setError(d.error);setBusy(false)}
  if(error&&!data)return <main className="contract-state">{error}</main>;if(!data)return <main className="contract-state"><LoaderCircle className="spin"/>Cargando contrato…</main>;if(data.signedAt||done)return <main className="contract-state success"><CheckCircle2/><h1>Contrato firmado</h1><p>La matrícula quedó activa y la copia PDF será enviada por correo.</p></main>;
  return <main className="contract-page"><article><header><FileSignature/><div><small>AULANOVA · CONTRATO DE MATRÍCULA</small><h1>{data.title}</h1></div></header><div className="contract-meta"><span><b>Curso</b>{data.course}</span><span><b>Docente</b>{data.teacher}</span><span><b>Estudiante</b>{data.studentName}</span></div><div className="contract-copy">{data.content.split("\n").map((p,i)=><p key={i} className={p.startsWith("IMPORTANTE")?"warning":""}>{p}</p>)}</div><form onSubmit={submit}><label>Nombre completo de quien firma<input name="signerName" defaultValue={data.signerName||""} required minLength={3}/></label><label>Firma manuscrita electrónica<div className="signature"><canvas ref={canvas} width={900} height={260} onPointerDown={start} onPointerMove={move} onPointerUp={()=>drawing.current=false}/><button type="button" onClick={clear}><Eraser/>Limpiar</button></div></label><label className="consent"><input type="checkbox" required/>Declaro que he leído, comprendido y acepto íntegramente este contrato y autorizo el resguardo de la firma como evidencia.</label>{error&&<p className="contract-error">{error}</p>}<button className="sign-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<FileSignature/>}{busy?"Guardando evidencia…":"Firmar y activar matrícula"}</button></form></article></main>;
}
