"use client";
import { useEffect, useMemo, useState } from "react";
import { Bell, BookOpen, CalendarDays, ChevronRight, CircleHelp, Clock3, FileText, GraduationCap, Home, Library, LogOut, MessageSquare, MoreHorizontal, Plus, Search, Settings, Sparkles, TrendingUp, Users } from "lucide-react";

type Role="Docente"|"Alumno"|"Administrador";
type Course={id:string;title:string;code:string;students:number;progress:number;color:string;modules:number;status:string};
type Stats={activeClassrooms:number;students:number;pending:number;average:number};
type Upcoming={id:string;title:string;date:string;classroom:{title:string;color:string}};

export default function HomePage(){
  const [role,setRole]=useState<Role>("Alumno"),[name,setName]=useState("Usuario"),[courses,setCourses]=useState<Course[]>([]),[stats,setStats]=useState<Stats>({activeClassrooms:0,students:0,pending:0,average:0}),[upcoming,setUpcoming]=useState<Upcoming[]>([]),[query,setQuery]=useState("");
  const filtered=useMemo(()=>courses.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())),[courses,query]);
  useEffect(()=>{Promise.all([fetch("/api/auth/me").then(r=>r.json()),fetch("/api/dashboard").then(r=>r.json())]).then(([account,data])=>{if(account.user){setName(account.user.name);setRole(account.user.role==="ADMIN"?"Administrador":account.user.role==="TEACHER"?"Docente":"Alumno")}if(data.stats)setStats(data.stats);if(data.upcoming)setUpcoming(data.upcoming);if(data.classrooms)setCourses(data.classrooms.map((item:{id:string;title:string;inviteCode:string;status:string;color:string;progress:number;_count:{enrollments:number;modules:number}})=>({id:item.id,title:item.title,code:item.inviteCode,students:item._count.enrollments,progress:item.progress,color:item.color,modules:item._count.modules,status:item.status})))})},[]);
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}
  const today=new Intl.DateTimeFormat("es",{weekday:"long",day:"numeric",month:"long"}).format(new Date()).toUpperCase();
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><GraduationCap size={23}/></span><span>Aula<span>Nova</span></span></div><div className="profile"><div className="avatar">{name.split(" ").map(p=>p[0]).join("").slice(0,2).toUpperCase()}<span/></div><div><strong>{name}</strong><small>{role}</small></div><button aria-label="Opciones"><MoreHorizontal size={18}/></button></div><div className="role-switch role-label">Vista de {role.toLowerCase()}</div><nav><p>ESPACIO DE TRABAJO</p><button className="active"><Home size={19}/><span>Inicio</span></button><button onClick={()=>location.href="/aulas"}><BookOpen size={19}/><span>Mis aulas</span></button><button onClick={()=>location.href="/calendario"}><CalendarDays size={19}/><span>Calendario</span></button><button onClick={()=>location.href="/notificaciones"}><MessageSquare size={19}/><span>Notificaciones</span></button><p>GESTIÓN</p><button onClick={()=>location.href="/aulas"}><Library size={19}/><span>Recursos</span></button>{role==="Administrador"&&<button onClick={()=>location.href="/admin/usuarios"}><Users size={19}/><span>Usuarios</span></button>}<button onClick={()=>location.href="/aulas"}><TrendingUp size={19}/><span>Calificaciones</span></button></nav><div className="sidebar-bottom"><button><CircleHelp size={19}/>Ayuda y soporte</button><button><Settings size={19}/>Configuración</button><button onClick={logout}><LogOut size={19}/>Cerrar sesión</button></div></aside>
  <section className="content"><header><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar aulas…"/></label><div className="header-actions"><button className="icon-btn" onClick={()=>location.href="/notificaciones"} aria-label="Notificaciones"><Bell size={20}/></button><button className="primary" onClick={()=>location.href=role==="Administrador"?"/admin/usuarios":role==="Docente"?"/aulas?action=create":"/aulas"}><Plus size={18}/>{role==="Docente"?"Crear aula":role==="Administrador"?"Nuevo usuario":"Unirme a un aula"}</button></div></header>
  <div className="body"><section className="welcome"><div><span className="eyebrow"><Sparkles size={14}/>{today}</span><h1>Buenos días, {name.split(" ")[0]} 👋</h1><p>{stats.pending?`Tienes ${stats.pending} actividades pendientes.`:"Todo está al día."}</p></div><div className="week"><b>Tu avance</b><small>información en tiempo real</small><span><i style={{width:`${stats.average}%`}}/></span><em>{stats.average}% promedio</em></div></section>
  <section className="stats"><article><span className="stat-icon purple"><BookOpen size={21}/></span><div><small>AULAS ACTIVAS</small><strong>{stats.activeClassrooms}</strong><em>Datos actuales</em></div></article><article><span className="stat-icon peach"><Users size={21}/></span><div><small>{role==="Alumno"?"AULAS INSCRITAS":"ESTUDIANTES"}</small><strong>{stats.students}</strong><em>Activos</em></div></article><article><span className="stat-icon green"><FileText size={21}/></span><div><small>{role==="Alumno"?"POR ENTREGAR":"POR REVISAR"}</small><strong>{stats.pending}</strong><em>Pendientes</em></div></article><article><span className="stat-icon yellow"><TrendingUp size={21}/></span><div><small>PROMEDIO GENERAL</small><strong>{stats.average}%</strong><em>Calificaciones</em></div></article></section>
  <div className="grid"><section><div className="section-title"><div><h2>Mis aulas</h2><p>Continúa donde lo dejaste</p></div><button onClick={()=>location.href="/aulas"}>Ver todas <ChevronRight size={16}/></button></div><div className="course-grid">{filtered.map(course=><article className="course-card" key={course.id} onClick={()=>location.href=`/aulas/${course.id}`}><div className="course-cover" style={{background:course.color}}><span>✦</span><label>{course.code}</label></div><div className="course-info"><h3>{course.title}</h3><p><Users size={15}/>{course.students} estudiantes</p><div className="progress-label"><span>Progreso</span><b>{course.progress}%</b></div><div className="bar"><i style={{width:`${course.progress}%`}}/></div><div className="next"><Clock3 size={16}/><div><small>CONTENIDO</small><strong>{course.modules} módulos</strong><span>{course.status==="ACTIVE"?"Aula publicada":"En preparación"}</span></div></div></div></article>)}{!filtered.length&&<p>No hay aulas para mostrar.</p>}</div></section>
  <aside className="activity-panel"><div className="section-title"><div><h2>Próximamente</h2><p>Tu agenda</p></div><button onClick={()=>location.href="/calendario"}><CalendarDays size={18}/></button></div>{upcoming.map(item=>{const date=new Date(item.date);return <div className="date-row" key={item.id}><div><b>{date.getDate()}</b><small>{date.toLocaleDateString("es",{month:"short"}).toUpperCase()}</small></div><span><strong>{item.title}</strong><small>{item.classroom.title} · {date.toLocaleTimeString("es",{hour:"2-digit",minute:"2-digit"})}</small></span><i className="dot violet"/></div>})}{!upcoming.length&&<p>No hay actividades próximas.</p>}<button className="agenda" onClick={()=>location.href="/calendario"}>Abrir calendario completo</button></aside></div></div></section></main>;
}
