"use client";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {FormEvent,use,useEffect,useMemo,useState} from "react";
import {ArrowLeft,CheckCircle2,Clock3,Download,FileText,GraduationCap,LoaderCircle,LockKeyhole,RotateCcw,Save,Send,UserRound} from "lucide-react";
import "./assignment.css";

type Submission={id:string;content:string|null;fileUrl:string|null;score:number|null;feedback:string|null;status:"DRAFT"|"SUBMITTED"|"REOPENED";submittedAt:string;updatedAt:string;student:{id:string;name:string;email:string}};
type Activity={id:string;title:string;description:string|null;dueAt:string|null;maxScore:number;type:string;lesson:{title:string;module:{title:string}};submissions:Submission[]};
type Data={role:string;classroom:{title:string;enrollments:{student:{id:string;name:string;email:string}}[]};activity:Activity};

export default function Assignment({params}:{params:Promise<{id:string;activityId:string}>}){
  const{id,activityId}=use(params),requestedStudent=useSearchParams().get("student")||"";const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[studentId,setStudentId]=useState(requestedStudent);
  async function load(){const response=await fetch(`/api/classrooms/${id}/activities/${activityId}`,{cache:"no-store"}),result=await response.json();if(response.ok){setData(result);setStudentId(current=>current||result.activity.submissions[0]?.student.id||result.classroom.enrollments[0]?.student.id||"")}setLoading(false)}
  useEffect(()=>{load()},[id,activityId]);
  const selected=useMemo(()=>data?.activity.submissions.find(item=>item.student.id===studentId),[data,studentId]);
  async function request(payload:object){setSaving(true);setError("");const response=await fetch(`/api/classrooms/${id}/activities/${activityId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok){setError(result.error);setSaving(false);return}await load();setSaving(false)}
  async function studentSubmit(form:HTMLFormElement,action:"save_draft"|"submit"){const fields=new FormData(form),file=fields.get("file");let fileUrl=data?.activity.submissions[0]?.fileUrl;if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);upload.set("classroomId",id);const response=await fetch("/api/storage/upload",{method:"POST",body:upload}),result=await response.json();if(!response.ok){setError(result.error);return}fileUrl=result.url}await request({action,content:fields.get("content"),fileUrl})}
  async function grade(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await request({action:"grade",submissionId:selected?.id,score:form.get("score"),feedback:form.get("feedback")})}
  if(loading)return <main className="assignment-state"><LoaderCircle className="spin"/>Cargando tarea…</main>;if(!data)return <main className="assignment-state">Tarea no encontrada.</main>;
  const activity=data.activity,submission=activity.submissions[0],due=activity.dueAt?new Date(activity.dueAt):null,late=!!(submission&&due&&new Date(submission.submittedAt)>due),locked=submission?.status==="SUBMITTED";
  return <main className="assignment-page"><header><Link href={`/aulas/${id}/tareas`}><ArrowLeft/>Todas las tareas</Link><span><GraduationCap/>Aula<b>Nova</b></span></header><div className="assignment-shell"><nav className="crumbs">{data.classroom.title}<b>›</b>{activity.lesson.module.title}<b>›</b>{activity.lesson.title}</nav><section className="assignment-hero"><div><small>{activity.type}</small><h1>{activity.title}</h1><p>{activity.description||"El docente no añadió instrucciones adicionales."}</p></div><div className="deadline"><Clock3/><span><small>FECHA LÍMITE</small><b>{due?due.toLocaleString("es"):"Sin fecha límite"}</b><em>{due?relative(due):"Disponible permanentemente"}</em></span></div></section>{data.role==="STUDENT"?<StudentView activity={activity} submission={submission} locked={locked} late={late} saving={saving} error={error} submit={studentSubmit}/>:<TeacherView data={data} selected={selected} studentId={studentId} setStudentId={setStudentId} grade={grade} reopen={()=>selected&&request({action:"reopen",submissionId:selected.id})} saving={saving} error={error}/>}</div></main>;
}
function relative(date:Date){const diff=date.getTime()-Date.now(),hours=Math.round(Math.abs(diff)/36e5);return diff<0?`Venció hace ${hours} h`:`Quedan ${hours} h`}
function Status({submission,late}:{submission?:Submission;late?:boolean}){const text=!submission?"Sin entrega":submission.status==="DRAFT"?"Borrador":submission.status==="REOPENED"?"Reabierta":late?"Enviada tarde":"Enviada para calificar";return <span className={`assignment-status ${submission?.status.toLowerCase()||"missing"}`}>{text}</span>}
function StudentView({activity,submission,locked,late,saving,error,submit:studentSubmit}:{activity:Activity;submission?:Submission;locked:boolean;late:boolean;saving:boolean;error:string;submit:(form:HTMLFormElement,action:"save_draft"|"submit")=>void}){
  return <div className="student-assignment"><section className="status-card"><h2>Estado de la entrega</h2><dl><div><dt>Estado</dt><dd><Status submission={submission} late={late}/></dd></div><div><dt>Estado de calificación</dt><dd>{submission?.score!=null?"Calificada":"Sin calificar"}</dd></div><div><dt>Última modificación</dt><dd>{submission?new Date(submission.updatedAt).toLocaleString("es"):"—"}</dd></div><div><dt>Calificación</dt><dd>{submission?.score!=null?<b>{submission.score} / {activity.maxScore}</b>:`— / ${activity.maxScore}`}</dd></div></dl>{submission?.feedback&&<aside><b>Retroalimentación del docente</b><p>{submission.feedback}</p></aside>}</section><form className="submission-editor" onSubmit={event=>{event.preventDefault();studentSubmit(event.currentTarget,"submit")}}><div className="editor-title"><div><h2>Mi entrega</h2><p>{locked?"La entrega está bloqueada después del envío definitivo.":"Guarda un borrador o envía el trabajo definitivamente."}</p></div>{locked&&<LockKeyhole/>}</div><label>Texto en línea<textarea name="content" defaultValue={submission?.content||""} disabled={locked} placeholder="Escribe aquí tu respuesta…"/></label><label className="drop-file"><FileText/><span><b>{submission?.fileUrl?"Reemplazar archivo":"Añadir archivo"}</b><small>PDF, documento, presentación, imagen, audio o video · máximo 25 MB</small></span><input name="file" type="file" disabled={locked}/></label>{submission?.fileUrl&&<a href={submission.fileUrl} target="_blank"><Download/>Descargar archivo actual</a>}{error&&<p className="assignment-error">{error}</p>}{!locked&&<div className="submission-actions"><button type="button" disabled={saving} onClick={event=>studentSubmit(event.currentTarget.form!,"save_draft")}><Save/>Guardar borrador</button><button disabled={saving}><Send/>{saving?"Guardando…":"Enviar definitivamente"}</button></div>}</form></div>;
}
function TeacherView({data,selected,studentId,setStudentId,grade,reopen,saving,error}:{data:Data;selected?:Submission;studentId:string;setStudentId:(value:string)=>void;grade:(event:FormEvent<HTMLFormElement>)=>void;reopen:()=>void;saving:boolean;error:string}){
  const submitted=data.activity.submissions.filter(item=>item.status==="SUBMITTED").length,graded=data.activity.submissions.filter(item=>item.score!=null).length;
  return <div className="grader-layout"><aside className="grader-list"><div className="grader-summary"><b>{submitted}/{data.classroom.enrollments.length}</b><span>entregadas</span><b>{submitted-graded}</b><span>por calificar</span></div>{data.classroom.enrollments.map(({student})=>{const item=data.activity.submissions.find(value=>value.student.id===student.id);const label=!item?"Sin entrega":item.status!=="SUBMITTED"?"Borrador":item.score==null?"Por calificar":"Calificada";return <button className={studentId===student.id?"active":""} key={student.id} onClick={()=>setStudentId(student.id)}><span><UserRound/></span><div><b>{student.name}</b><small>{label}</small></div>{item?.score!=null&&<em>{item.score}</em>}</button>})}</aside><section className="grading-panel">{selected?<><div className="grading-head"><div><small>ENTREGA DE</small><h2>{selected.student.name}</h2><p>{selected.student.email} · {new Date(selected.updatedAt).toLocaleString("es")}</p></div><Status submission={selected}/></div><article className="submitted-content"><h3>Texto en línea</h3><p>{selected.content||"Sin texto en línea."}</p>{selected.fileUrl&&<a href={selected.fileUrl} target="_blank"><Download/>Abrir archivo entregado</a>}</article>{selected.status==="SUBMITTED"?<form onSubmit={grade}><div className="score-field"><label>Calificación<input name="score" type="number" min="0" max={data.activity.maxScore} step="0.01" defaultValue={selected.score??""} required/></label><b>/ {data.activity.maxScore}</b></div><label>Retroalimentación<textarea name="feedback" defaultValue={selected.feedback||""} placeholder="Escribe observaciones útiles para el estudiante…"/></label>{error&&<p className="assignment-error">{error}</p>}<div className="grading-actions"><button type="button" onClick={reopen}><RotateCcw/>Reabrir entrega</button><button disabled={saving}><CheckCircle2/>{saving?"Guardando…":"Guardar calificación"}</button></div></form>:<div className="not-ready"><LockKeyhole/><p>Esta entrega todavía no fue enviada definitivamente.</p><button onClick={reopen}>Permitir edición</button></div>}</>:<div className="not-ready"><FileText/><p>Este estudiante todavía no realizó una entrega.</p></div>}</section></div>;
}
