CREATE TABLE "QuizQuestion" ("id" TEXT NOT NULL,"prompt" TEXT NOT NULL,"options" JSONB NOT NULL,"correctAnswer" TEXT NOT NULL,"points" DOUBLE PRECISION NOT NULL DEFAULT 1,"position" INTEGER NOT NULL,"activityId" TEXT NOT NULL,CONSTRAINT "QuizQuestion_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "QuizQuestion_activityId_position_key" ON "QuizQuestion"("activityId","position");
CREATE TABLE "QuizAttempt" ("id" TEXT NOT NULL,"answers" JSONB NOT NULL,"score" DOUBLE PRECISION NOT NULL,"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"activityId" TEXT NOT NULL,"studentId" TEXT NOT NULL,CONSTRAINT "QuizAttempt_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "QuizAttempt_activityId_studentId_key" ON "QuizAttempt"("activityId","studentId");
CREATE TABLE "ForumPost" ("id" TEXT NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"activityId" TEXT NOT NULL,"authorId" TEXT NOT NULL,CONSTRAINT "ForumPost_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LessonProgress" ("id" TEXT NOT NULL,"completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lessonId" TEXT NOT NULL,"studentId" TEXT NOT NULL,CONSTRAINT "LessonProgress_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "LessonProgress_lessonId_studentId_key" ON "LessonProgress"("lessonId","studentId");
CREATE TABLE "CalendarEvent" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3),"kind" TEXT NOT NULL DEFAULT 'CLASS',"classroomId" TEXT NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CalendarEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"href" TEXT,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"userId" TEXT NOT NULL,CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
ALTER TABLE "QuizQuestion" ADD CONSTRAINT "QuizQuestion_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QuizAttempt" ADD CONSTRAINT "QuizAttempt_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QuizAttempt" ADD CONSTRAINT "QuizAttempt_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ForumPost" ADD CONSTRAINT "ForumPost_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ForumPost" ADD CONSTRAINT "ForumPost_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LessonProgress" ADD CONSTRAINT "LessonProgress_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
