"use client";
import Link from "next/link";
import {FormEvent,use,useEffect,useMemo,useState} from "react";
import {ArrowLeft,CheckCircle2,Clock3,Download,FileText,GraduationCap,LoaderCircle,Search,Send,Users,XCircle} from "lucide-react";
import "./tasks.css";

type Submission={id:string;content:string|null;fileUrl:string|null;score:number|null;feedback:string|null;submittedAt:string;student:{id:string;name:string;email:string}};
type Activity={id:string;title:string;description:string|null;type:string;dueAt:string|null;maxScore:number;submissions:Submission[]};
type Lesson={title:string;activities:Activity[]};type Classroom={title:string;enrollments:{student:{id:string;name:string;email:string}}[];modules:{lessons:Lesson[]}[]};

export default function TasksCenter({params}:{params:Promise<{id:string}>}){
  const{id}=use(params),[classroom,setClassroom]=useState<Classroom|null>(null),[role,setRole]=useState("STUDENT"),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Activity|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function load(){const response=await fetch(`/api/classrooms/${id}`,{cache:"no-store"}),data=await response.json();if(response.ok){setClassroom(data.classroom);setRole(data.role)}setLoading(false)}useEffect(()=>{load()},[id]);
  const activities=useMemo(()=>classroom?.modules.flatMap(module=>module.lessons.flatMap(lesson=>lesson.activities.map(activity=>({...activity,lesson:lesson.title}))))??[],[classroom]);
  async function submitWork(event:FormEvent<HTMLFormElement>,activity:Activity){event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget),file=form.get("file");let fileUrl="";if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);upload.set("classroomId",id);const response=await fetch("/api/storage/upload",{method:"POST",body:upload}),result=await response.json();if(!response.ok){setError(result.error);setSaving(false);return}fileUrl=result.url}const response=await fetch(`/api/classrooms/${id}/content`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submission",activityId:activity.id,content:form.get("content"),fileUrl})}),result=await response.json();if(!response.ok){setError(result.error);setSaving(false);return}await load();setSelected(null);setSaving(false)}
  async function grade(event:FormEvent<HTMLFormElement>,submissionId:string){event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget),response=await fetch(`/api/classrooms/${id}/content`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"grade",submissionId,score:form.get("score"),feedback:form.get("feedback")})}),result=await response.json();if(!response.ok){setError(result.error);setSaving(false);return}await load();setSelected(null);setSaving(false)}
  if(loading)return <main className="tasks-state"><LoaderCircle className="spin"/>Cargando tareas…</main>;if(!classroom)return <main className="tasks-state">No tienes acceso.</main>;
  return <main className="tasks-page"><header className="tasks-header"><Link href={`/aulas/${id}`}><ArrowLeft/>Volver al aula</Link><span><GraduationCap/>Aula<b>Nova</b></span></header><div className="tasks-wrap"><section className="tasks-heading"><div><small>CENTRO DE ACTIVIDADES</small><h1>Tareas de {classroom.title}</h1><p>{role==="STUDENT"?"Consulta instrucciones, entrega tu trabajo y revisa la retroalimentación.":"Revisa el avance de todo el grupo y califica desde un solo lugar."}</p></div><div className="tasks-summary"><article><Users/><b>{role==="STUDENT"?activities.length:classroom.enrollments.length}</b><span>{role==="STUDENT"?"Actividades":"Participantes"}</span></article><article><Send/><b>{activities.reduce((sum,item)=>sum+item.submissions.length,0)}</b><span>Entregas</span></article><article><CheckCircle2/><b>{activities.reduce((sum,item)=>sum+item.submissions.filter(s=>s.score!=null).length,0)}</b><span>Calificadas</span></article></div></section>{role==="STUDENT"?<StudentTasks activities={activities} open={setSelected}/>:<TeacherTasks activities={activities} students={classroom.enrollments} query={query} setQuery={setQuery} status={status} setStatus={setStatus} open={setSelected}/>}</div>{selected&&<TaskModal activity={selected} role={role} close={()=>setSelected(null)} submitWork={submitWork} grade={grade} saving={saving} error={error}/>}</main>;
}

function timing(activity:Activity,submission?:Submission){const due=activity.dueAt?new Date(activity.dueAt):null,late=!!(due&&submission&&new Date(submission.submittedAt)>due),overdue=!!(due&&!submission&&Date.now()>due.getTime());return{due,late,overdue}}
function StudentTasks({activities,open}:{activities:(Activity&{lesson:string})[];open:(a:Activity)=>void}){return <section className="student-task-grid">{activities.map(activity=>{const submission=activity.submissions[0],time=timing(activity,submission),state=submission?.score!=null?"GRADED":submission?"SUBMITTED":time.overdue?"OVERDUE":"PENDING";return <article className="student-task-card" key={activity.id}><div className="task-card-top"><span className={`status ${state.toLowerCase()}`}>{state==="GRADED"?"Calificada":state==="SUBMITTED"?time.late?"Entregada tarde":"Entregada":"Sin entrega"}</span><small>{activity.lesson}</small></div><h2>{activity.title}</h2><p>{activity.description||"Sin instrucciones adicionales."}</p><dl><div><dt>Fecha límite</dt><dd>{time.due?time.due.toLocaleString("es"):"Sin fecha límite"}</dd></div><div><dt>Última modificación</dt><dd>{submission?new Date(submission.submittedAt).toLocaleString("es"):"—"}</dd></div><div><dt>Calificación</dt><dd>{submission?.score!=null?`${submission.score} / ${activity.maxScore}`:"Pendiente"}</dd></div></dl>{submission?.feedback&&<div className="feedback"><b>Retroalimentación</b><p>{submission.feedback}</p></div>}<button onClick={()=>open(activity)}>{submission?.score!=null?"Ver entrega":submission?"Editar entrega":"Añadir entrega"}</button></article>})}{!activities.length&&<div className="tasks-empty">No hay tareas publicadas.</div>}</section>}
function TeacherTasks({activities,students,query,setQuery,status,setStatus,open}:{activities:(Activity&{lesson:string})[];students:Classroom["enrollments"];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;open:(a:Activity)=>void}){return <section className="teacher-activities">{activities.map(activity=>{const submitted=activity.submissions.length,graded=activity.submissions.filter(s=>s.score!=null).length,pending=submitted-graded;return <details key={activity.id} open><summary><div><small>{activity.lesson} · {activity.type}</small><h2>{activity.title}</h2><span>{activity.dueAt?`Vence ${new Date(activity.dueAt).toLocaleString("es")}`:"Sin fecha límite"}</span></div><div className="activity-counts"><b>{submitted}/{students.length}<small>Entregadas</small></b><b>{pending}<small>Por calificar</small></b><b>{graded}<small>Calificadas</small></b></div></summary><div className="table-tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar estudiante…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Todos los estados</option><option value="MISSING">Sin entrega</option><option value="PENDING">Por calificar</option><option value="GRADED">Calificadas</option></select></div><div className="submission-table"><div className="table-row table-head"><span>Estudiante</span><span>Estado</span><span>Entrega</span><span>Calificación</span><span>Acción</span></div>{students.filter(e=>e.student.name.toLowerCase().includes(query.toLowerCase())).map(enrollment=>{const submission=activity.submissions.find(s=>s.student.name===enrollment.student.name),state=!submission?"MISSING":submission.score==null?"PENDING":"GRADED";if(status!=="ALL"&&status!==state)return null;const time=timing(activity,submission);return <div className="table-row" key={enrollment.student.id}><span><b>{enrollment.student.name}</b><small>{enrollment.student.email}</small></span><span><i className={`status ${state.toLowerCase()}`}>{state==="MISSING"?"Sin entrega":state==="PENDING"?time.late?"Tarde · por calificar":"Por calificar":"Calificada"}</i></span><span>{submission?<><b>{new Date(submission.submittedAt).toLocaleDateString("es")}</b><small>{submission.fileUrl?"Archivo adjunto":"Texto en línea"}</small></>:"—"}</span><span>{submission?.score!=null?`${submission.score}/${activity.maxScore}`:"—"}</span><span>{submission?<button onClick={()=>open({...activity,submissions:[submission]})}>{submission.score==null?"Calificar":"Revisar"}</button>:<em>No disponible</em>}</span></div>})}</div></details>})}{!activities.length&&<div className="tasks-empty">No hay tareas publicadas.</div>}</section>}
function TaskModal({activity,role,close,submitWork,grade,saving,error}:{activity:Activity;role:string;close:()=>void;submitWork:(e:FormEvent<HTMLFormElement>,a:Activity)=>void;grade:(e:FormEvent<HTMLFormElement>,id:string)=>void;saving:boolean;error:string}){const submission=activity.submissions[0];return <div className="task-modal-bg" onMouseDown={close}><div className="task-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><XCircle/></button><small>{activity.type}</small><h2>{activity.title}</h2><p>{activity.description||"Sin instrucciones adicionales."}</p>{role==="STUDENT"?<form onSubmit={e=>submitWork(e,activity)}><label>Texto de la entrega<textarea name="content" defaultValue={submission?.content||""} placeholder="Escribe tu respuesta o una nota para el docente…"/></label><label>Archivo<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.mp4,.mp3,.docx,.pptx"/></label>{submission?.fileUrl&&<a href={submission.fileUrl} target="_blank"><Download/>Descargar archivo enviado</a>}{submission?.score!=null?<div className="modal-grade"><b>{submission.score}/{activity.maxScore}</b><p>{submission.feedback||"Sin retroalimentación."}</p></div>:<button disabled={saving}><Send/>{saving?"Guardando…":submission?"Actualizar entrega":"Enviar tarea"}</button>}</form>:submission?<form onSubmit={e=>grade(e,submission.id)}><div className="submitted-work"><h3>Trabajo enviado por {submission.student.name}</h3><p>{submission.content||"Sin texto en línea."}</p>{submission.fileUrl&&<a href={submission.fileUrl} target="_blank"><FileText/>Abrir archivo adjunto</a>}</div><label>Calificación sobre {activity.maxScore}<input name="score" type="number" min="0" max={activity.maxScore} step="0.01" defaultValue={submission.score??""} required/></label><label>Retroalimentación<textarea name="feedback" defaultValue={submission.feedback||""}/></label><button disabled={saving}><CheckCircle2/>{saving?"Guardando…":"Guardar calificación"}</button></form>:null}{error&&<p className="modal-error">{error}</p>}</div></div>}
