CREATE TYPE "SubmissionStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'REOPENED');
ALTER TABLE "Submission" ADD COLUMN "status" "SubmissionStatus" NOT NULL DEFAULT 'SUBMITTED';
ALTER TABLE "Submission" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Submission" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
